import { TrendingTransfersCardType } from '@/utils/types/airport-transfers';

export const data: TrendingTransfersCardType[] = [
  {
    name: 'Gimpo International Airport (GMP)',
    price: 'From $50',
    _id: 'ChIJF6qs-dCcfDURVMw5Ij-Qd6w',
    des_from:
      'Gimpo International Airport (GMP), Haneul-gil, Gangseo-gu, Seoul, South Korea',
    from_type: 'airport',
    lat: 37.55865449999999,
    lng: 126.7944739,
    origin_country: 'South Korea',
  },
  {
    name: 'Melbourne Airport (MEL)',
    _id: 'ChIJFzmq66lZ1moRkPAvBXZWBA8',
    des_from: 'Melbourne Airport (MEL), Melbourne Airport VIC, Australia',
    price: 'From $65',
    from_type: 'airport',
    lat: -37.6708673,
    lng: 144.8432785,
    origin_country: 'Australia',
  },
  {
    name: 'Chhatrapati Shivaji International Airport (BOM)',
    _id: 'ChIJRym9mVDI5zsRrqh0xGAazB4',
    des_from:
      'Chhatrapati Shivaji Maharaj International Airport (BOM), Mumbai, Maharashtra, India',
    price: 'From $20',
    from_type: 'airport',
    lat: 19.0903694,
    lng: 72.86275189999999,
    origin_country: 'India',
  },
  {
    name: 'Ngurah Rai International Airport (DPS)',
    _id: 'ChIJM2khUBZE0i0RH8x73W3acd8',
    des_from:
      'Bandar Udara Internasional Ngurah Rai (DPS), Jalan Raya Gusti Ngurah Rai, Tuban, Badung Regency, Bali, Indonesia',
    price: 'From $15',
    from_type: 'airport',
    lat: -8.746717199999999,
    lng: 115.166787,
    origin_country: 'Indonesia',
  },
  {
    name: 'King Khalid International Airport (RUH)',
    _id: 'ChIJ2-1ZHvnwLj4R1RcTUX978us',
    des_from:
      'King Khalid International Airport (RUH), Airport Road, Riyadh Saudi Arabia',
    price: 'From $65',
    from_type: 'airport',
    lat: 24.9635827,
    lng: 46.7006598,
    origin_country: 'Saudi Arabia',
  },
  {
    name: 'Noi Bai International Airport (HAN)',
    _id: 'ChIJU8SvORUCNTERtCYCUqP64OY',
    des_from: 'Noi Bai International Airport (HAN), Sóc Sơn, Hanoi, Vietnam',
    price: 'From $100',
    from_type: 'airport',
    lat: 21.2187149,
    lng: 105.8041709,
    origin_country: 'Vietnam',
  },
  {
    name: 'King Abdulaziz International Airport - Terminal 1 (JED)',
    des_from:
      'King Abdulaziz International Airport - Terminal 1 (JED), السبعين، Jeddah Saudi Arabia',
    _id: 'ChIJw3sEoivYwxURf0T5OpwjpzA',
    price: 'From $50',
    from_type: 'airport',
    lat: 21.6614237,
    lng: 39.1738055,
    origin_country: 'Saudi Arabia',
  },
  {
    name: 'Gimhae International Airport (PUS)',
    des_from:
      'Gimhae International Airport (PUS), Gonghangjinim-ro, Gangseo-gu, Busan, South Korea',
    _id: 'ChIJDfcSIsGSaDUR7DKMmkKpoxU',
    price: 'From $80',
    from_type: 'airport',
    lat: 35.17322,
    lng: 128.9464591,
    origin_country: 'South Korea',
  },
  {
    name: 'Cape Town International Airport (CPT)',
    _id: 'ChIJvQtA90JFzB0RkF7P43l1SEA',
    des_from:
      'Cape Town International Airport (CPT), Matroosfontein, Cape Town, South Africa',
    price: 'From $20',
    from_type: 'airport',
    lat: -33.971463,
    lng: 18.6020851,
    origin_country: 'South Africa',
  },
  {
    name: 'Brisbane Airport (BNE)',
    _id: 'ChIJb5rRQ__hk2sREHAg11ujAg8',
    des_from:
      'Brisbane Airport (BNE), Airport Drive, Brisbane Airport QLD, Australia',
    price: 'From $40',
    from_type: 'airport',
    lat: -27.3942144,
    lng: 153.1218303,
    origin_country: 'Australia',
  },
  {
    name: 'Shanghai Hongqiao International Airport',
    _id: 'ChIJ_-mi5Y1msjUR9tm8h7eW1dI',
    des_from:
      'Shanghai Hongqiao International Airport, 虹桥路长宁区 Shanghai, China',
    price: 'From $35',
    from_type: 'airport',
    lat: 31.19220900000001,
    lng: 121.334297,
    origin_country: 'China',
  },
  {
    name: 'Copenhagen Airport',
    _id: 'ChIJa5WHJxCrU0YRC7NaIP-8lfw',
    des_from: 'Copenhagen Airport, Lufthavnsboulevarden, Kastrup, Denmark',
    price: 'From $90',
    from_type: 'airport',
    lat: 55.6123217,
    lng: 12.6472251,
    origin_country: 'Denmark',
  },
];
